version: "3"
services:
  rebels:
    image: rebels:latest
    ### ATTENZIONE ###
    # Il nome del container deve essere fissato a 'rebels'
    #
    # Esporre pubblicamente la porta 5000 del container
    # https://docs.docker.com/compose/compose-file/
    build:
      context: ./rebels
      dockerfile: Dockerfile
    container_name: rebels
    ports:
      - "5001:5000"
    volumes:
      - /Users/yesh/Downloads/job-challenge-beginners-main/starwars/rebels:/app
    networks:
      - starwars

  deathstar:
    image: deathstar:latest
    ### ATTENZIONE ###
    # Il nome del container deve essere fissato a 'ds1'
    #
    # Il servizio deathstar deve essere dipendente dall'avvio del servizio 'rebels'
    # https://docs.docker.com/compose/compose-file/
    build:
      context: ./deathstar
      dockerfile: Dockerfile
    container_name: ds1
    ports:
      - "5002:5000"
    volumes:
      - /Users/yesh/Downloads/job-challenge-beginners-main/starwars/deathstar:/app
    networks:
      - starwars

networks:
  starwars:
