global:
  scrape_interval: 3s

scrape_configs:
  ### ATTENZIONE ###
  # Configurare un job di nome "prometheus" che avrà come target l'istanza prometheus
  # Configurare un altro job, di nome "starwars", che come target avrà l'applicativo python rebels
  - job_name: "prometheus"
    static_configs:
      - targets: ["15.207.72.177:9090"]
  - job_name: "starwars"
    static_configs:
      - targets: ["localhost:5000"]
