---
- hosts: localhost
  become: yes

  tasks:

    - name: Install Prometheus
      ### ATTENZIONE ###
      # Completare il task andando ad inserire l'istruzione per l'installazione di un nuovo pacchetto
      # il nome del pacchetto è 'prometheus'

    - name: Prometheus configuration file
      template:
        ### ATTENZIONE ###
        # Completare il task andando ad inserire nel template i corretti valori per andare a creare un nuovo file di configurazione
        # chiamato "/etc/prometheus/prometheus.yml", con il contenuto del file config.yml.
        # Il mode deve essere 0755 e owner e group uguale a prometheus

    - name: Restart Prometheus
      systemd:
        ### ATTENZIONE ###
        # Completare il task andando a eseguire il restart del servizio 'prometheus'
        # effettua il reload dei demoni e ricorda inoltre di abilitare il servizio all'avvio.